server:
  port: 8000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iBryukh/config-properties
          searchPaths: gateway-service, user-service, device-service, authentication-service
